# Generated by Django 5.0.2 on 2024-02-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buzzapp', '0003_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourname', models.CharField(max_length=100)),
                ('youremail', models.EmailField(max_length=100)),
                ('subject', models.EmailField(max_length=100)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
    ]
