# Generated by Django 5.0.2 on 2024-02-28 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buzzapp', '0004_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='youremail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='yourname',
            new_name='name',
        ),
    ]
